/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/forecast": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Прогноз посадок с применением условий */
        post: operations["postForecast"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/forecast/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Тот же прогноз файлом
         * @description Тело запроса совпадает с `/api/v1/forecast`. Выгружается именно то, что на экране:
         *     те же маршруты, период, квант и условия. Имя файла приходит в `Content-Disposition`,
         *     клиент сохраняет blob.
         */
        post: operations["postForecastExport"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/explain": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Разбор одной клетки
         * @description Весь путь одного значения: календарь, признаки в том виде, в каком они ушли
         *     в модель, сырой выход, обрезка нуля, калибровка, каждое условие отдельной строкой,
         *     итог. Вызывается по клику на столбец графика или клетку тепловой карты.
         */
        post: operations["postExplain"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/conditions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Каталог условий с паспортами
         * @description Отдаётся при старте интерфейса: из него строятся карточки условий, пределы
         *     ползунков и подсказки. Прогноз не считается.
         */
        get: operations["getConditions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/routes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Маршруты, названия, наличие геометрии */
        get: operations["getRoutes"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/model": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Версия бандла и метаданные обучения */
        get: operations["getModel"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Счётчики запросов и ресурсы процесса */
        get: operations["getStats"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Готовность
         * @description Отвечает 200 только когда бандл загружен и прошёл проверки целостности.
         */
        get: operations["getHealthz"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description Номер маршрута. Маршрут 5 - оценка: истории по нему нет.
         * @enum {integer}
         */
        RouteNumber: 1 | 5 | 7 | 11 | 12 | 17 | 25 | 26 | 28 | 50;
        /**
         * Format: date
         * @description Дата в пределах области определения, 2025-01-01 ... 2026-04-30.
         * @example 2025-11-11
         */
        IsoDate: string;
        /**
         * @description Квант ряда. При `hour` период не больше 31 суток.
         * @enum {string}
         */
        Granularity: "hour" | "day";
        /**
         * @description Влияет на применимость условий и на ширину коридора, но не на модель: модель одна.
         *     На `month` и `season` оперативные условия не применяются - сохраняются с
         *     `applied: false` и предупреждением.
         * @enum {string}
         */
        Horizon: "day" | "week" | "month" | "season";
        /**
         * @description Оперативные (множитель в единицы процентов, живут на `day` и `week`):
         *     `rain` - осадки, мм/ч;
         *     `temperature` - отклонение от нормы, градусы Цельсия;
         *     `event` - событие рядом, процент задаёт оператор;
         *     `delay` - пост о задержке трамваев.
         *     Структурные (меняют сеть, живут на всех горизонтах):
         *     `closure` - отмена или перекрытие;
         *     `route_change` - изменение маршрута на участке.
         * @enum {string}
         */
        ConditionType: "rain" | "temperature" | "event" | "delay" | "closure" | "route_change";
        /** @enum {string} */
        ConditionClass: "operational" | "structural";
        /** @description Где и когда условие действует. Все поля независимы и применяются вместе. */
        Scope: {
            /** @description `null` - все маршруты запроса. */
            routes?: components["schemas"]["RouteNumber"][] | null;
            /**
             * @description Явный список дат. Шаблоны вида «все будни» разворачивает клиент перед
             *     отправкой: сервер шаблонов не понимает. `null` - все даты периода.
             */
            dates?: components["schemas"]["IsoDate"][] | null;
            /** @description Понедельник - 1. Дополнительный фильтр к датам. */
            weekdays?: number[] | null;
            /**
             * @description Пара [от, до] включительно. `null` - все часы.
             * @example [
             *       16,
             *       22
             *     ]
             */
            hours?: number[] | null;
        };
        ConditionInput: {
            /** @description Задаёт клиент; возвращается в аудите и в предупреждениях. */
            id: string;
            type: components["schemas"]["ConditionType"];
            /**
             * @description Значение в единицах паспорта: мм/ч для `rain`, градусы отклонения для
             *     `temperature`, проценты для `event`, доля отмены для `closure`.
             *     Допустимый диапазон - в каталоге.
             */
            value: number;
            scope?: components["schemas"]["Scope"];
        };
        ForecastRequest: {
            /** @description Пусто или отсутствует - все десять. */
            routes?: components["schemas"]["RouteNumber"][];
            from: components["schemas"]["IsoDate"];
            to: components["schemas"]["IsoDate"];
            granularity: components["schemas"]["Granularity"];
            horizon: components["schemas"]["Horizon"];
            /**
             * @description Считать границы коридора. При `false` поля `lo` и `hi` не приходят.
             * @default true
             */
            corridor: boolean;
            /** @default [] */
            conditions: components["schemas"]["ConditionInput"][];
        };
        /** @description Все массивы одной длины; время точки i = `start + i * step`. */
        Series: {
            route: components["schemas"]["RouteNumber"];
            /** @description Прогноз до применения условий. */
            base: number[];
            /** @description Прогноз после условий. При пустом сценарии совпадает с `base`. */
            value: number[];
            /**
             * @description Обычный уровень для этого маршрута, дня недели и часа. Нужен карте:
             *     цвет линии - это `value / usual`, то есть процент от обычного уровня,
             *     а не заполнение салона.
             */
            usual: number[];
            /** @description Нижняя граница коридора; приходит при `corridor: true`. */
            lo?: number[];
            /**
             * @description Верхняя граница коридора. Превышение (`value > hi`) - это то, что
             *     показывается кольцами на карте и строками в тревогах.
             */
            hi?: number[];
            base_total: number;
            total: number;
            /** @description Индекс максимума в `value`. */
            peak_index: number;
        };
        /**
         * @description Паспорт условия: он же показывается при наведении. Смысл - показать, что
         *     величина измерена на истории с интервалом, а не взята из головы.
         */
        Passport: {
            /** @example мм/ч */
            unit: string;
            /** @example 0.2 */
            step?: number;
            /** @example Open-Meteo ERA5 */
            source: string;
            /** Format: uri */
            source_url?: string;
            /**
             * @description Точечный эффект в процентах; для выбранного маршрута, если он один.
             * @example -5.4
             */
            effect_pct: number;
            /**
             * @example [
             *       -10,
             *       0
             *     ]
             */
            ci_pct: number[];
            /** @example 1953 */
            sample?: number;
            horizons: components["schemas"]["Horizon"][];
            class: components["schemas"]["ConditionClass"];
        };
        AppliedCondition: {
            id: string;
            type: components["schemas"]["ConditionType"];
            /**
             * @description `false` означает, что условие сохранено, но не применено - например, оперативное
             *     условие на горизонте месяц. Прогноз при этом не изменён, а в `warnings` лежит
             *     запись с тем же `condition_id`. Клиент показывает карточку серой, а не удаляет.
             */
            applied: boolean;
            /**
             * @description Множитель условия. Композиция условий - произведение, порядок не важен.
             * @example 0.936
             */
            factor: number;
            /**
             * @description Вклад в изменение суммы по всему выбору, проценты.
             * @example -1.4
             */
            contribution_pct: number;
            /** @description Сколько точек ряда попало в область условия. */
            points: number;
            /**
             * @description Почасовой профиль эффекта, 24 значения. Заполняется только когда запрошен
             *     один маршрут и одни сутки: на месяце по десяти маршрутам это в разы больше
             *     данных, чем сам прогноз. В остальных случаях `null`.
             */
            profile?: number[] | null;
            passport: components["schemas"]["Passport"];
        };
        Warning: {
            /**
             * @description `condition_not_applicable_on_horizon` - оперативное условие на месяце или сезоне;
             *     `condition_scope_empty` - область условия не пересеклась с периодом запроса;
             *     `correction_clamped` - произведение условий вышло за коридор корректировки
             *     и было ограничено, значение указано в сообщении;
             *     `route_without_history` - в выборке есть маршрут 5, его значения - оценка.
             * @enum {string}
             */
            code: "condition_not_applicable_on_horizon" | "condition_scope_empty" | "correction_clamped" | "route_without_history";
            condition_id?: string | null;
            /** @description Русский текст, пригодный к показу как есть. */
            message: string;
        };
        /** @description Миллисекунды. */
        Timings: {
            parse?: number;
            features?: number;
            model?: number;
            corrections?: number;
            json?: number;
        };
        Meta: {
            /** @description Сколько строк ушло в модель. */
            rows: number;
            /** @example catboost_cyclic_service */
            model: string;
            timings: components["schemas"]["Timings"];
        };
        ForecastResponse: {
            /** @example 2025-11-10T00:00 */
            start: string;
            /** @enum {string} */
            step: "1h" | "1d" | "1mo";
            /** @example 2026-09-27T09:12:00Z/8f3a1c */
            bundle: string;
            series: components["schemas"]["Series"][];
            conditions: components["schemas"]["AppliedCondition"][];
            warnings: components["schemas"]["Warning"][];
            meta: components["schemas"]["Meta"];
        };
        ExplainRequest: {
            route: components["schemas"]["RouteNumber"];
            date: components["schemas"]["IsoDate"];
            hour: number;
            /** @default [] */
            conditions: components["schemas"]["ConditionInput"][];
        };
        ExplainStep: {
            /** @description Например: сырой выход модели, обрезка нуля, калибровка, условие c1. */
            step: string;
            detail?: string;
            factor?: number | null;
            value: number;
        };
        ExplainResponse: {
            route: components["schemas"]["RouteNumber"];
            date: components["schemas"]["IsoDate"];
            hour: number;
            /** @description Флаги производственного календаря на эту дату. */
            calendar: {
                [key: string]: unknown;
            };
            /** @description Признаки в том виде, в каком они ушли в модель, в порядке подачи. */
            features: {
                name: string;
                value: unknown;
                /** @enum {string} */
                kind?: "float" | "categorical";
                hash?: number | null;
            }[];
            steps: components["schemas"]["ExplainStep"][];
            value: number;
        };
        CatalogEntry: {
            type: components["schemas"]["ConditionType"];
            class: components["schemas"]["ConditionClass"];
            /** @example Дождь */
            title?: string;
            passport: components["schemas"]["Passport"];
            /** @description Эффект по маршрутам; при выборе нескольких маршрутов берётся общий. */
            by_route?: {
                [key: string]: components["schemas"]["Passport"];
            };
            /** @description Пределы ползунка в единицах паспорта. */
            range: {
                min: number;
                max: number;
                step?: number;
            };
            /**
             * @description Применяется ли условие автоматически из данных. Сейчас `false` у всех шести,
             *     и это измеренное решение: автоматическая поправка на дождь двигает почасовой
             *     WAPE на +0.013 пункта [-0.044; +0.065], то есть ни на что, а фиксированные
             *     температурные коэффициенты делают хуже. Сами эффекты при этом значимы на истории.
             * @default false
             */
            auto: boolean;
        };
        Route: {
            route: components["schemas"]["RouteNumber"];
            /** @example Бульвар Рокоссовского - Белорусский вокзал */
            name: string;
            /**
             * @description Есть ли линия в `web/geo/routes.geojson`. Маршруты без геометрии живут в
             *     списках и графиках, но не на карте.
             */
            has_geometry: boolean;
            /** @description `false` у маршрута 5: его значения получены городским профилем. */
            has_history: boolean;
            /** @enum {string} */
            geometry_source?: "spravochnik" | "osm" | "none";
        };
        ModelInfo: {
            bundle: string;
            model: string;
            /**
             * @description `service` - погоды в модели нет, она приходит условием; так работает дашборд.
             *     `metric` - погода признаками; этим бандлом собран CSV для платформы. Одновременно
             *     режимы не применяются: эффект считался бы дважды.
             * @enum {string}
             */
            mode?: "service" | "metric";
            features: string[];
            cat_features?: string[];
            train_period: components["schemas"]["IsoDate"][];
            /** @description Область определения по датам, 2025-01-01 ... 2026-04-30. */
            horizon: components["schemas"]["IsoDate"][];
            /** @example 0.8882 */
            wape_score?: number;
        };
        Stats: {
            requests?: number;
            rows?: number;
            rps_1m?: number;
            p50_ms?: number;
            p95_ms?: number;
            cpu_pct?: number;
            rss_mb?: number;
            uptime_s?: number;
        };
        Error: {
            error: {
                /** @enum {string} */
                code: "bad_request" | "unauthorized" | "period_too_long" | "too_many_rows" | "too_many_conditions" | "out_of_domain" | "internal";
                /** @description Русский текст, пригодный к показу как есть. */
                message: string;
                /** @description Поле запроса, вызвавшее ошибку. */
                field?: string;
            };
        };
    };
    responses: {
        /** @description Неверный запрос */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": {
                 *         "code": "out_of_domain",
                 *         "message": "Дата 2026-07-01 вне области определения модели, доступно до 2026-04-30",
                 *         "field": "to"
                 *       }
                 *     }
                 */
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Нет авторизации */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Запрос превышает пределы */
        TooLarge: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": {
                 *         "code": "period_too_long",
                 *         "message": "По часам доступен период не больше 31 суток, запрошено 61",
                 *         "field": "granularity"
                 *       }
                 *     }
                 */
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Внутренняя ошибка */
        ServerError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: {
        /**
         * @description Разбивка времени обработки, те же величины, что в `meta.timings`.
         * @example parse;dur=0.1, features;dur=0.6, model;dur=1.2, corrections;dur=0.2, json;dur=0.4
         */
        ServerTiming: string;
    };
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    postForecast: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ForecastRequest"];
            };
        };
        responses: {
            /** @description Прогноз посчитан */
            200: {
                headers: {
                    "Server-Timing": components["headers"]["ServerTiming"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ForecastResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            413: components["responses"]["TooLarge"];
            500: components["responses"]["ServerError"];
        };
    };
    postForecastExport: {
        parameters: {
            query: {
                format: "csv" | "xlsx";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ForecastRequest"];
            };
        };
        responses: {
            /** @description Файл выгрузки */
            200: {
                headers: {
                    /** @description Например: attachment; filename="forecast_2025-11-11_r7.csv" */
                    "Content-Disposition"?: string;
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example route;date;hour;base;prediction;lo;hi
                     *     7;2025-11-11;0;41;41;33;50
                     */
                    "text/csv": string;
                    "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet": string;
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            413: components["responses"]["TooLarge"];
        };
    };
    postExplain: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExplainRequest"];
            };
        };
        responses: {
            /** @description Разбор */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExplainResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    getConditions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Каталог */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        conditions: components["schemas"]["CatalogEntry"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    getRoutes: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Маршруты */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        routes: components["schemas"]["Route"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    getModel: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Метаданные */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelInfo"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    getStats: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Счётчики */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Stats"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    getHealthz: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Готов */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {string} */
                        status: "ok";
                        /** @example 2026-09-27T09:12:00Z/8f3a1c */
                        bundle: string;
                    };
                };
            };
            /** @description Бандл не загружен */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
}
