/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/forecast": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Прогноз посадок с применением условий */
        post: operations["postForecast"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/forecast/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Тот же прогноз файлом
         * @description Тело запроса совпадает с `/api/v1/forecast`. Выгружается именно то, что на экране:
         *     те же маршруты, период, квант, модель и условия. Имя файла приходит в
         *     `Content-Disposition`, клиент сохраняет blob.
         *
         *     Колонки: по часам `route;date;hour;base;factor;prediction[;lo;hi]`, по суткам
         *     `route;date;base;factor;prediction[;lo;hi]`. Числа округлены так же, как в JSON;
         *     `factor` - отношение прогноза после условий к прогнозу до них, 4 знака (1 при нулевом
         *     `base`); `lo;hi` только при `corridor: true`. CSV разделён `;`, в UTF-8.
         *     В XLSX лист `Прогноз` с теми же колонками (числа - числами) и, если в запросе есть
         *     условия, лист `Условия`: `id, тип, применено, множитель, вклад_%, точек`.
         */
        post: operations["postForecastExport"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/explain": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Разбор одной клетки
         * @description Весь путь одного значения: календарь, признаки в том виде, в каком они ушли
         *     в модель, сырой выход, обрезка нуля, калибровка, новогодний блок, каждое условие
         *     отдельной строкой, итог. Вызывается по клику на столбец графика или клетку тепловой
         *     карты. Для маршрута 5 модель не вызывается ни у одной из моделей: `features` пуст,
         *     шаги начинаются со строки `маршрут 5` (городская доля).
         */
        post: operations["postExplain"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/conditions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Каталог условий с паспортами
         * @description Отдаётся при старте интерфейса: из него строятся карточки условий, пределы
         *     ползунков и подсказки. Прогноз не считается.
         */
        get: operations["getConditions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/routes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Маршруты, названия, наличие геометрии */
        get: operations["getRoutes"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/model": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Модели сервиса, версии бандлов и метаданные обучения */
        get: operations["getModel"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/geo/routes.geojson": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Линии маршрутов для карты
         * @description GeoJSON из `web/geo/routes.geojson` как есть.
         */
        get: operations["getRoutesGeo"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Счётчики запросов и ресурсы процесса */
        get: operations["getStats"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Готовность
         * @description Отвечает 200, когда бандлы всех моделей прочитаны и прошли проверки целостности.
         *     Если проверка не прошла, сервер не стартует, поэтому другого ответа у этой точки нет.
         */
        get: operations["getHealthz"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description Номер маршрута. Маршрут 5 - оценка: истории по нему нет.
         * @enum {integer}
         */
        RouteNumber: 1 | 5 | 7 | 11 | 12 | 17 | 25 | 26 | 28 | 50;
        /**
         * Format: date
         * @description Дата в пределах области определения выбранной модели: CatBoost - 2025-01-01 ...
         *     2026-04-30, CNN - 2025-11-01 ... 2026-04-30.
         * @example 2025-11-11
         */
        IsoDate: string;
        /**
         * @description Квант ряда. При `hour` период не больше 31 суток.
         * @enum {string}
         */
        Granularity: "hour" | "day";
        /**
         * @description Влияет на применимость условий и на ширину коридора, но не на выход модели.
         *     На `month` и `season` оперативные условия не применяются - сохраняются с
         *     `applied: false` и предупреждением.
         * @enum {string}
         */
        Horizon: "day" | "week" | "month" | "season";
        /**
         * @description Оперативные (множитель в единицы процентов, живут на `day` и `week`):
         *     `rain` - осадки, мм/ч;
         *     `temperature` - отклонение от нормы, градусы Цельсия;
         *     `event` - событие рядом, процент задаёт оператор;
         *     `delay` - пост о задержке трамваев.
         *     Структурные (меняют сеть, живут на всех горизонтах):
         *     `closure` - отмена или перекрытие;
         *     `route_change` - изменение маршрута на участке.
         * @enum {string}
         */
        ConditionType: "rain" | "temperature" | "event" | "delay" | "closure" | "route_change";
        /** @enum {string} */
        ConditionClass: "operational" | "structural";
        /** @description Где и когда условие действует. Все поля независимы и применяются вместе. */
        Scope: {
            /** @description `null` - все маршруты запроса. */
            routes?: components["schemas"]["RouteNumber"][] | null;
            /**
             * @description Явный список дат. Шаблоны вида «все будни» разворачивает клиент перед
             *     отправкой: сервер шаблонов не понимает. `null` - все даты периода.
             */
            dates?: components["schemas"]["IsoDate"][] | null;
            /** @description Понедельник - 1. Дополнительный фильтр к датам. */
            weekdays?: number[] | null;
            /**
             * @description Пара [от, до] включительно. `null` - все часы.
             * @example [
             *       16,
             *       22
             *     ]
             */
            hours?: number[] | null;
        };
        ConditionInput: {
            /** @description Задаёт клиент; возвращается в аудите и в предупреждениях. */
            id: string;
            type: components["schemas"]["ConditionType"];
            /**
             * @description Значение в единицах паспорта: мм/ч для `rain`, градусы отклонения для
             *     `temperature`, проценты для `event`, доля отмены для `closure`.
             *     Допустимый диапазон - в каталоге.
             */
            value: number;
            scope?: components["schemas"]["Scope"];
        };
        /**
         * @description Какая модель считает прогноз. `catboost` - профильная модель без лагов, область
         *     2025-01-01 ... 2026-04-30. `cnn` - сеть с контекстом 14 суток истории до 2025-11-01,
         *     область 2025-11-01 ... 2026-04-30: до 2025-12-31 прямой прогноз, с 2026-01-01
         *     авторегрессия, посчитанная при сборке бандла. Условия, коридор, обычный уровень, разбор и
         *     выгрузка работают одинаково для обеих.
         * @default catboost
         * @enum {string}
         */
        ModelName: "catboost" | "cnn";
        ForecastRequest: {
            model?: components["schemas"]["ModelName"];
            /** @description Пусто или отсутствует - все десять. */
            routes?: components["schemas"]["RouteNumber"][];
            from: components["schemas"]["IsoDate"];
            to: components["schemas"]["IsoDate"];
            granularity: components["schemas"]["Granularity"];
            horizon: components["schemas"]["Horizon"];
            /**
             * @description Считать границы коридора. При `false` поля `lo` и `hi` не приходят.
             * @default true
             */
            corridor: boolean;
            /** @default [] */
            conditions: components["schemas"]["ConditionInput"][];
        };
        /** @description Все массивы одной длины; время точки i = `start + i * step`. */
        Series: {
            route: components["schemas"]["RouteNumber"];
            /** @description Прогноз до применения условий. */
            base: number[];
            /** @description Прогноз после условий. При пустом сценарии совпадает с `base`. */
            value: number[];
            /**
             * @description Обычный уровень для этого маршрута, дня недели и часа. Нужен карте:
             *     цвет линии - это `value / usual`, то есть процент от обычного уровня,
             *     а не заполнение салона.
             */
            usual: number[];
            /** @description Нижняя граница коридора; приходит при `corridor: true`. */
            lo?: number[];
            /**
             * @description Верхняя граница коридора. Превышение (`value > hi`) - это то, что
             *     показывается кольцами на карте и строками в тревогах.
             */
            hi?: number[];
            base_total: number;
            total: number;
            /** @description Индекс максимума в `value`. */
            peak_index: number;
        };
        /**
         * @description Паспорт условия: он же показывается при наведении. Смысл - показать, что
         *     величина измерена на истории с интервалом, а не взята из головы.
         */
        Passport: {
            /** @example мм/ч */
            unit: string;
            /** @example 0.2 */
            step?: number;
            /** @example Open-Meteo ERA5 */
            source: string;
            /** Format: uri */
            source_url?: string;
            /**
             * @description Точечный эффект в процентах; для выбранного маршрута, если он один.
             * @example -5.4
             */
            effect_pct: number;
            /**
             * @example [
             *       -10,
             *       0
             *     ]
             */
            ci_pct: number[];
            /** @example 1953 */
            sample?: number;
            horizons: components["schemas"]["Horizon"][];
            class: components["schemas"]["ConditionClass"];
        };
        AppliedCondition: {
            id: string;
            type: components["schemas"]["ConditionType"];
            /**
             * @description `false` означает, что условие сохранено, но не применено - например, оперативное
             *     условие на горизонте месяц. Прогноз при этом не изменён, а в `warnings` лежит
             *     запись с тем же `condition_id`. Клиент показывает карточку серой, а не удаляет.
             */
            applied: boolean;
            /**
             * @description Множитель условия. Композиция условий - произведение, порядок не важен.
             * @example 0.936
             */
            factor: number;
            /**
             * @description Вклад в изменение суммы по всему выбору, проценты.
             * @example -1.4
             */
            contribution_pct: number;
            /** @description Сколько точек ряда попало в область условия. */
            points: number;
            /**
             * @description Почасовой профиль эффекта, 24 значения. Заполняется только когда запрошен
             *     один маршрут и одни сутки: на месяце по десяти маршрутам это в разы больше
             *     данных, чем сам прогноз. В остальных случаях `null`.
             */
            profile?: number[] | null;
            passport: components["schemas"]["Passport"];
        };
        Warning: {
            /**
             * @description `condition_not_applicable_on_horizon` - оперативное условие на месяце или сезоне;
             *     `condition_scope_empty` - область условия не пересеклась с периодом запроса;
             *     `correction_clamped` - произведение условий вышло за коридор корректировки
             *     и было ограничено, значение указано в сообщении;
             *     `route_without_history` - в выборке есть маршрут 5, его значения - оценка.
             * @enum {string}
             */
            code: "condition_not_applicable_on_horizon" | "condition_scope_empty" | "correction_clamped" | "route_without_history";
            condition_id?: string | null;
            /** @description Русский текст, пригодный к показу как есть. */
            message: string;
        };
        /** @description Миллисекунды. */
        Timings: {
            parse?: number;
            features?: number;
            model?: number;
            corrections?: number;
        };
        Meta: {
            /**
             * @description Сколько строк ушло в модель, включая пересчёт обычного уровня для необычных дней.
             *     Предел 50 000 строк на запрос считается по строкам прогноза без этого пересчёта,
             *     поэтому `rows` бывает больше 50 000.
             */
            rows: number;
            /** @example catboost_cyclic_service */
            model: string;
            timings: components["schemas"]["Timings"];
        };
        ForecastResponse: {
            /** @example 2025-11-10T00:00 */
            start: string;
            /** @enum {string} */
            step: "1h" | "1d";
            /** @example 2026-09-27T09:12:00Z/8f3a1c */
            bundle: string;
            series: components["schemas"]["Series"][];
            conditions: components["schemas"]["AppliedCondition"][];
            warnings: components["schemas"]["Warning"][];
            meta: components["schemas"]["Meta"];
        };
        ExplainRequest: {
            model?: components["schemas"]["ModelName"];
            route: components["schemas"]["RouteNumber"];
            date: components["schemas"]["IsoDate"];
            hour: number;
            /**
             * @description Горизонт, на котором применяются условия, как в прогнозе.
             * @default day
             */
            horizon: components["schemas"]["Horizon"];
            /** @default [] */
            conditions: components["schemas"]["ConditionInput"][];
        };
        ExplainStep: {
            /**
             * @description Например: сырой выход модели, обрезка нуля, калибровка, маршрут 5, новогодний
             *     блок, условие c1, коридор корректировки.
             */
            step: string;
            detail?: string;
            factor?: number | null;
            value: number;
        };
        ExplainResponse: {
            model: components["schemas"]["ModelName"];
            route: components["schemas"]["RouteNumber"];
            date: components["schemas"]["IsoDate"];
            hour: number;
            /** @description Флаги производственного календаря на эту дату. */
            calendar: {
                [key: string]: unknown;
            };
            /** @description Признаки в том виде, в каком они ушли в модель, в порядке подачи. */
            features: {
                name: string;
                value: unknown;
                /** @enum {string} */
                kind?: "float" | "categorical";
                hash?: number | null;
            }[];
            steps: components["schemas"]["ExplainStep"][];
            value: number;
            /**
             * @description Аудит условий по всем 24 часам этого маршрута и дня, как в прогнозе на эти
             *     сутки, а не только по одной клетке.
             */
            conditions: components["schemas"]["AppliedCondition"][];
            warnings: components["schemas"]["Warning"][];
        };
        CatalogEntry: {
            type: components["schemas"]["ConditionType"];
            class: components["schemas"]["ConditionClass"];
            /** @example Дождь */
            title?: string;
            passport: components["schemas"]["Passport"];
            /** @description Эффект по маршрутам; при выборе нескольких маршрутов берётся общий. */
            by_route?: {
                [key: string]: components["schemas"]["Passport"];
            };
            /** @description Пределы ползунка в единицах паспорта. */
            range: {
                min: number;
                max: number;
                step?: number;
            };
            /**
             * @description Применяется ли условие автоматически из данных. Сейчас `false` у всех шести,
             *     и это измеренное решение: автоматическая поправка на дождь двигает почасовой
             *     WAPE на +0.013 пункта [-0.044; +0.065], то есть ни на что, а фиксированные
             *     температурные коэффициенты делают хуже. Сами эффекты при этом значимы на истории.
             * @default false
             */
            auto: boolean;
            /**
             * @description Кривая эффекта: пары [значение в единицах паспорта, эффект в процентах],
             *     кусочно-линейная; повтор x - ступенька. Между точками значение интерполируется,
             *     за краями берётся крайняя точка.
             * @example [
             *       [
             *         0,
             *         0
             *       ],
             *       [
             *         0.05,
             *         0
             *       ],
             *       [
             *         0.05,
             *         -2.2
             *       ],
             *       [
             *         0.3,
             *         -2.2
             *       ],
             *       [
             *         0.3,
             *         -6.4
             *       ]
             *     ]
             */
            curve?: number[][];
        };
        Route: {
            route: components["schemas"]["RouteNumber"];
            /** @example Бульвар Рокоссовского - Белорусский вокзал */
            name: string;
            /**
             * @description Есть ли линия в `web/geo/routes.geojson`. Маршруты без геометрии живут в
             *     списках и графиках, но не на карте.
             */
            has_geometry: boolean;
            /** @description `false` у маршрута 5: его значения получены городским профилем. */
            has_history: boolean;
            /** @enum {string} */
            geometry_source?: "spravochnik" | "osm" | "none";
        };
        /**
         * @description Метаданные бандла модели: поля `meta.json` как есть плюс `name`, `bundle`, `describe`
         *     и `files`. У каждой модели могут быть свои дополнительные поля (у CNN - `cutoff`,
         *     `history_days`, `parameters`, `validation`).
         */
        ModelInfo: {
            name: components["schemas"]["ModelName"];
            bundle: string;
            /** @example catboost_cyclic_service */
            model: string;
            /**
             * @description Короткое описание модели для интерфейса.
             * @example CatBoost, 625 деревьев
             */
            describe: string;
            /** @description Файлы бандла с размером и SHA-256, проверенные при старте. */
            files: {
                name: string;
                size: number;
                sha256: string;
            }[];
            /**
             * @description `service` - погоды в модели нет, она приходит условием. Сервис читает только такие
             *     бандлы: метрический бандл с погодой признаками (им собран CSV для платформы) не
             *     экспортируется, иначе эффект погоды считался бы дважды.
             * @enum {string}
             */
            mode?: "service";
            features: string[];
            cat_features?: string[];
            train_period: components["schemas"]["IsoDate"][];
            /** @description Область определения по датам. */
            horizon: components["schemas"]["IsoDate"][];
            /**
             * @description 1 - WAPE вне обучения: у CatBoost - на фолдах 3 и 4 до калибровки, у CNN - у
             *     валидационной модели на 61 сутках с 2025-09-01.
             * @example 0.8929
             */
            wape_score?: number;
        } & {
            [key: string]: unknown;
        };
        Stats: {
            /** @description Успешные запросы прогноза, выгрузки и разбора с запуска. */
            requests: number;
            /** @description Ответы с ошибкой с запуска, включая 401. */
            errors: number;
            /** @description Сколько строк прошло через модели с запуска. */
            rows: number;
            /** @description Успешных запросов в секунду за последнюю минуту. */
            rps_1m: number;
            /**
             * @description Медиана времени обработки по последним успешным запросам: не больше 4096 последних
             *     и не старше минуты; 0 без запросов.
             */
            p50_ms: number;
            /** @description Квантиль 0.95 по той же выборке, что `p50_ms`. */
            p95_ms: number;
            /** @description CPU процесса с предыдущего вызова `/api/v1/stats`, процент одного ядра. */
            cpu_pct: number;
            /**
             * @description На Linux - резидентная память процесса. На других системах - память рантайма Go
             *     (`runtime.MemStats.Sys`), без памяти библиотеки CatBoost.
             */
            rss_mb: number;
            uptime_s: number;
        };
        Error: {
            error: {
                /** @enum {string} */
                code: "bad_request" | "unauthorized" | "period_too_long" | "too_many_rows" | "too_many_conditions" | "out_of_domain" | "internal";
                /** @description Русский текст, пригодный к показу как есть. */
                message: string;
                /** @description Поле запроса, вызвавшее ошибку. */
                field?: string;
            };
        };
    };
    responses: {
        /** @description Неверный запрос */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": {
                 *         "code": "out_of_domain",
                 *         "message": "Дата 01.07.2026 вне области определения модели catboost, доступно до 30.04.2026",
                 *         "field": "to"
                 *       }
                 *     }
                 */
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Нет авторизации */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Запрос превышает пределы */
        TooLarge: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": {
                 *         "code": "period_too_long",
                 *         "message": "По часам доступен период не больше 31 суток, запрошено 61",
                 *         "field": "granularity"
                 *       }
                 *     }
                 */
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Внутренняя ошибка */
        ServerError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: {
        /**
         * @description Разбивка времени обработки: те же величины, что в `meta.timings`, плюс `json` -
         *     сериализация ответа, которая есть только в заголовке.
         * @example parse;dur=0.1, features;dur=0.6, model;dur=1.2, corrections;dur=0.2, json;dur=0.4
         */
        ServerTiming: string;
    };
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    postForecast: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ForecastRequest"];
            };
        };
        responses: {
            /** @description Прогноз посчитан */
            200: {
                headers: {
                    "Server-Timing": components["headers"]["ServerTiming"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ForecastResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            413: components["responses"]["TooLarge"];
            500: components["responses"]["ServerError"];
        };
    };
    postForecastExport: {
        parameters: {
            query: {
                format: "csv" | "xlsx";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ForecastRequest"];
            };
        };
        responses: {
            /** @description Файл выгрузки */
            200: {
                headers: {
                    /**
                     * @description Имя файла: `forecast_<model>_<from>[_<to>]_<routes>.<ext>`, где `<to>` есть
                     *     только у периода длиннее суток, а `<routes>` - `all` для всех десяти маршрутов
                     *     или `r` и номера через дефис. Например:
                     *     `attachment; filename="forecast_catboost_2025-11-11_r7.csv"`.
                     */
                    "Content-Disposition"?: string;
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example route;date;hour;base;factor;prediction;lo;hi
                     *     7;2025-11-11;0;41;1;41;33;50
                     */
                    "text/csv": string;
                    "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet": string;
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            413: components["responses"]["TooLarge"];
            500: components["responses"]["ServerError"];
        };
    };
    postExplain: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExplainRequest"];
            };
        };
        responses: {
            /** @description Разбор */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExplainResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            /** @description Больше 16 условий или тело запроса больше 1 МБ */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            500: components["responses"]["ServerError"];
        };
    };
    getConditions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Каталог */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        conditions: components["schemas"]["CatalogEntry"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    getRoutes: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Маршруты */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        routes: components["schemas"]["Route"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    getModel: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Метаданные обеих моделей */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /**
                         * @description Модель, которая считает запрос без поля `model`.
                         * @example catboost
                         */
                        default: string;
                        models: components["schemas"]["ModelInfo"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    getRoutesGeo: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description FeatureCollection с линиями маршрутов */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/geo+json": Record<string, never>;
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    getStats: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Счётчики */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Stats"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    getHealthz: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Готов */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {string} */
                        status: "ok";
                        /**
                         * @description Версия бандла модели по умолчанию.
                         * @example 2026-09-27T09:12:00Z/8f3a1c
                         */
                        bundle: string;
                        /**
                         * @description Версия бандла каждой модели сервиса.
                         * @example {
                         *       "catboost": "2026-09-27T09:12:00Z/8f3a1c",
                         *       "cnn": "2026-09-27T10:40:00Z/8c16e8"
                         *     }
                         */
                        models: {
                            [key: string]: string;
                        };
                    };
                };
            };
        };
    };
}
