flowchart TB
    A[Плотная почасовая сетка] --> B[Признаки: календарь, sin/cos,<br/>праздничные блоки, погода]
    B --> M1[catboost_cyclic]
    B --> M2[catboost_base]
    B --> M3[harmonic]
    B --> M4[mlp]
    M1 & M2 & M3 & M4 --> O[Прогнозы вне обучения<br/>на фолдах 3 и 4]
    O --> W[Подбор весов на симплексе<br/>0.7 CatBoost + 0.3 MLP]
    W --> RF[Переобучение на январе-октябре]
    RF --> K[Поправка маршрут x день недели<br/>снята на октябре вне обучения]
    K --> P[Постобработка:<br/>маршрут 5, новогодний блок]
    P --> S[Файл прогноза, 14 640 строк]
